apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-director.fullname" . }}
  labels:
    {{- include "pod-director.labels" . | nindent 4 }}
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ include "pod-director.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-director.clusterRoleName" . }}
