{{- $labelKeyRegex := "^([a-z0-9]([-a-z0-9]*[a-z0-9])?\\.)*([a-z0-9]([-a-z0-9]*[a-z0-9])?\\/)?[a-z0-9]([-a-z0-9]*[a-z0-9])?$" }}
{{- $labelValueRegex := "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$" }}
{{- $groupLabel := .Values.config.groupLabel }}
{{- if $groupLabel }}
  {{- if gt (len $groupLabel) 63 }}
    {{- fail (printf "The group label '%s' is longer than the maximum length 63 for labels" $groupLabel) }}
  {{- end }}
  {{- if not (mustRegexMatch $labelKeyRegex $groupLabel) }}
    {{- fail (printf "The group label '%s' is not a valid label" $groupLabel) }}
  {{- end }}
{{- end }}
{{- range $groupName := keys .Values.config.groups }}
  {{- if gt (len $groupName) 63 }}
    {{- fail (printf "The group name '%s' is longer than the maximum length 63 for label values" $groupName) }}
  {{- end }}
  {{- if not (mustRegexMatch $labelValueRegex $groupName) }}
    {{- fail (printf "The group name '%s' is not a valid label value and thus cannot be a group name" $groupName) }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-director.configMapName" . }}
  labels:
    {{- include "pod-director.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.config.filename | quote }}: |
    server:
      {{- toYaml .Values.config.server | nindent 6 }}
    groups:
      {{- toYaml .Values.config.groups | nindent 6 }}
    {{- with $groupLabel }}
    groupLabel: {{ . | quote }}
    {{- end }}
