apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pod-director.configMapName" . }}
  labels:
    {{- include "pod-director.labels" . | nindent 4 }}
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ .Values.config.filename | quote }}: |
    server:
      {{- toYaml .Values.config.server | nindent 6 }}
    groups:
      {{- toYaml .Values.config.groups | nindent 6 }}
