apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-director.serviceAccountName" . }}
  labels:
    {{- include "pod-director.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
